import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CoverTune",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {  
  const messages = await getMessages();
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextIntlClientProvider messages={messages}>
      {children}
      </NextIntlClientProvider>
      </body>
    </html>
  );
}
